.PHONY: test_run

test_run:
	SLACK_BOT_TOKEN=${TEST_SLACK_BOT_TOKEN} \
	SLACK_OUTGOING_TOKEN=${TEST_SLACK_OUTGOING_TOKEN} \
	FLICKR_API_TOKEN=${TEST_FLICKR_API_TOKEN} \
	TUMBLR_API_TOKEN=${TEST_TUMBLR_API_TOKEN} \
	go run functions/bot/*.go

run:
	SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN} \
	SLACK_OUTGOING_TOKEN=${SLACK_OUTGOING_TOKEN} \
	FLICKR_API_TOKEN=${FLICKR_API_TOKEN} \
	TUMBLR_API_TOKEN=${TUMBLR_API_TOKEN} \
	go run functions/bot/*.go

deploy:
	apex deploy \
		-s SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN} \
		-s SLACK_OUTGOING_TOKEN=${SLACK_OUTGOING_TOKEN} \
		-s FLICKR_API_TOKEN=${FLICKR_API_TOKEN} \
		-s TUMBLR_API_TOKEN=${TUMBLR_API_TOKEN} bot
